// Which sources back which facts. Every figure cites the two textual sources;
// the astronomical-dating source is attached to the war's opening event, where
// its dating argument is most relevant.

export const mahabharatFigureCitations = mahabharatFigureSlugs().flatMap((figureSlug) => [
  { figureSlug, sourceKey: "bori-critical-edition" as const },
  { figureSlug, sourceKey: "debroy-translation" as const },
]);

export const mahabharatEventCitations = [
  { eventSlug: "shantanu-and-ganga", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "bhishmas-vow", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "bhishmas-vow", sourceKey: "debroy-translation" as const },
  { eventSlug: "amba-and-the-brides", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "the-niyoga-births", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "the-niyoga-births", sourceKey: "debroy-translation" as const },
  { eventSlug: "pandu-and-the-curse", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "birth-of-the-pandavas", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "birth-of-the-pandavas", sourceKey: "debroy-translation" as const },
  { eventSlug: "birth-of-the-kauravas", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "the-trial-of-arms", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "the-trial-of-arms", sourceKey: "debroy-translation" as const },
  { eventSlug: "karna-at-the-tournament", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "the-house-of-lac", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "draupadis-swayamvara", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "draupadis-swayamvara", sourceKey: "debroy-translation" as const },
  { eventSlug: "the-rajasuya", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "the-exile-and-disguise", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "the-exile-and-disguise", sourceKey: "debroy-translation" as const },
  { eventSlug: "game-of-dice", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "krishnas-peace-embassy", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "bhagavad-gita", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "bhagavad-gita", sourceKey: "debroy-translation" as const },
  {
    eventSlug: "bhagavad-gita",
    sourceKey: "achar-astronomical-dating" as const,
    note: "Discusses dating the war's start via the eclipses described around this point in the narrative.",
  },
  { eventSlug: "bhagavad-gita", sourceKey: "easwaran-gita" as const },
  { eventSlug: "fall-of-bhishma", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "death-of-abhimanyu", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "jayadrathas-death", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "death-of-ghatotkacha", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "death-of-dushasana", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "fall-of-drona", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "death-of-karna", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "death-of-duryodhana", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "ashwatthamas-night-raid", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "sorrow-of-victory", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "bhishmas-final-teaching", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "bhishmas-final-teaching", sourceKey: "debroy-translation" as const },
  { eventSlug: "great-departure", sourceKey: "bori-critical-edition" as const },
  { eventSlug: "great-departure", sourceKey: "debroy-translation" as const },
];

function mahabharatFigureSlugs() {
  return [
    "krishna",
    "arjuna",
    "karna",
    "bhishma",
    "draupadi",
    "duryodhana",
    "yudhishthira",
    "bhima",
    "shakuni",
    "abhimanyu",
    "shantanu",
    "ganga",
    "satyavati",
    "vyasa",
    "dhritarashtra",
    "pandu",
    "vidura",
    "amba",
    "kunti",
    "madri",
    "gandhari",
    "drona",
    "ekalavya",
    "ashwatthama",
    "nakula",
    "sahadeva",
    "drupada",
    "dhrishtadyumna",
    "shikhandi",
    "dushasana",
    "jayadratha",
    "ghatotkacha",
    "subhadra",
  ];
}
