// All public domain: verified against each file's Wikimedia Commons page
// (pre-1931 publication or copyright term expired). Downloaded to
// public/assets/mahabharat/ — see task notes for source file page URLs.

export const mahabharatMedia = [
  {
    key: "krishna-figure",
    figureSlug: "krishna",
    filePathOrUrl: "/assets/mahabharat/krishna-envoy.jpg",
    caption: "Krishna as Envoy",
    credit: "Raja Ravi Varma, 1905 — Wikimedia Commons",
    license: "Public domain (artist d. 1906)",
  },
  {
    key: "arjuna-figure",
    figureSlug: "arjuna",
    filePathOrUrl: "/assets/mahabharat/arjuna-krishna-chariot.jpg",
    caption: "Krishna and Arjuna on the chariot",
    credit: "Unknown artist, 18th–19th c. India — Smithsonian Freer|Sackler, via Wikimedia Commons",
    license: "Public domain",
  },
  {
    key: "karna-figure",
    figureSlug: "karna",
    filePathOrUrl: "/assets/mahabharat/karna-portrait.jpg",
    caption: "Arjuna and Karna",
    credit: "M A Joshi & Co., 1920s — Wikimedia Commons",
    license: "Public domain",
  },
  {
    key: "bhishma-figure",
    figureSlug: "bhishma",
    filePathOrUrl: "/assets/mahabharat/bhishma-oath.jpg",
    caption: "Bhishma's Oath",
    credit: "Raja Ravi Varma — Wikimedia Commons",
    license: "Public domain (artist d. 1906)",
  },
  {
    key: "draupadi-figure",
    figureSlug: "draupadi",
    filePathOrUrl: "/assets/mahabharat/draupadi-portrait.jpg",
    caption: "Draupadi and the Pandavas",
    credit: "Raja Ravi Varma, c. 1910 — Wikimedia Commons",
    license: "Public domain (PD-India)",
  },
  {
    key: "game-of-dice-event",
    eventSlug: "game-of-dice",
    filePathOrUrl: "/assets/mahabharat/draupadi-vastraharan.jpg",
    caption: "Draupadi Vastraharan",
    credit: "Raja Ravi Varma, c. 1888–90 — Wikimedia Commons",
    license: "Public domain (artist d. 1906)",
  },
  {
    key: "peace-embassy-event",
    eventSlug: "krishnas-peace-embassy",
    filePathOrUrl: "/assets/mahabharat/krishna-peace-embassy.jpg",
    caption: "Krishna Pleads with Dhritarashtra to Avoid War",
    credit: "Raja Ravi Varma — Wikimedia Commons",
    license: "Public domain (PD-India)",
  },
  {
    key: "bhagavad-gita-event",
    eventSlug: "bhagavad-gita",
    filePathOrUrl: "/assets/mahabharat/arjuna-krishna-chariot.jpg",
    caption: "Krishna and Arjuna on the chariot",
    credit: "Unknown artist, 18th–19th c. India — Smithsonian Freer|Sackler, via Wikimedia Commons",
    license: "Public domain",
  },
  {
    key: "fall-of-bhishma-event",
    eventSlug: "fall-of-bhishma",
    filePathOrUrl: "/assets/mahabharat/death-of-bhishma.jpg",
    caption: "The Death of Bhishma",
    credit: "Unknown artist, c. 1650 — Smithsonian Institution, via Wikimedia Commons",
    license: "Public domain",
  },
  {
    key: "death-of-karna-event",
    eventSlug: "death-of-karna",
    filePathOrUrl: "/assets/mahabharat/karna-death.jpg",
    caption: "Arjuna and His Charioteer Krishna Confront Karna",
    credit: "Unknown artist, c. 1820, Pahari school — Wikimedia Commons",
    license: "Public domain",
  },
  {
    key: "kurukshetra-location",
    locationSlug: "kurukshetra",
    filePathOrUrl: "/assets/mahabharat/kurukshetra-map.png",
    caption: "Kurukshetra district within Haryana, India",
    credit: "Milenioscuro — Wikimedia Commons",
    license: "CC BY-SA 4.0",
  },
  {
    key: "duryodhana-figure",
    figureSlug: "duryodhana",
    filePathOrUrl: "/assets/mahabharat/duryodhana-portrait.jpg",
    caption: "Duryodhana",
    credit: "Raja Ravi Varma, 1906 — Wikimedia Commons",
    license: "Public domain (artist d. 1906)",
  },
  {
    key: "abhimanyu-figure",
    figureSlug: "abhimanyu",
    filePathOrUrl: "/assets/mahabharat/abhimanyu-relief.jpg",
    caption: "Abhimanyu entering the Chakravyuha, carved in stone",
    credit: "Hoysaleswara Temple, Halebidu, 12th century — Wikimedia Commons",
    license: "CC BY-SA 3.0 / GFDL",
  },
  {
    key: "death-of-abhimanyu-event",
    eventSlug: "death-of-abhimanyu",
    filePathOrUrl: "/assets/mahabharat/abhimanyu-relief.jpg",
    caption: "Abhimanyu entering the Chakravyuha, carved in stone",
    credit: "Hoysaleswara Temple, Halebidu, 12th century — Wikimedia Commons",
    license: "CC BY-SA 3.0 / GFDL",
  },
  {
    key: "death-of-duryodhana-event",
    eventSlug: "death-of-duryodhana",
    filePathOrUrl: "/assets/mahabharat/duryodhana-bhima-duel.png",
    caption: "The mace duel between Bhima and Duryodhana",
    credit: "Kamal, Razmnama manuscript, 1616–17 — Wikimedia Commons",
    license: "Public domain (PD-India)",
  },
  {
    key: "artifact-khanda",
    filePathOrUrl: "/assets/mahabharat/khanda-sword.jpg",
    caption: "A khanda, the straight double-edged sword of the subcontinent",
    credit: "Archit Patel — Wikimedia Commons",
    license: "Public domain",
  },
  {
    key: "artifact-dhal",
    filePathOrUrl: "/assets/mahabharat/dhal-shield.jpg",
    caption: "A dhal — the round shield carried across ancient and medieval India",
    credit: "The Metropolitan Museum of Art, via Wikimedia Commons",
    license: "CC BY 2.0",
  },
  {
    key: "artifact-chariot-wheel",
    filePathOrUrl: "/assets/mahabharat/konark-chariot-wheel.jpg",
    caption: "A carved stone chariot wheel, Konark Sun Temple",
    credit: "SamhitaB — Wikimedia Commons",
    license: "CC BY-SA 4.0",
  },
  {
    key: "texture-parchment-light",
    type: "texture",
    filePathOrUrl: "/assets/textures/parchment-light.jpg",
    caption: "Aged parchment (light-mode surface texture)",
    credit: "James Puckett — Wikimedia Commons",
    license: "CC BY 2.0",
  },
  {
    key: "texture-parchment-dark",
    type: "texture",
    filePathOrUrl: "/assets/textures/parchment-dark.jpg",
    caption: "Worn book pages (dark-mode surface texture)",
    credit: "D. Sharon Pruitt (Pink Sherbet Photography) — Wikimedia Commons",
    license: "CC BY 2.0",
  },
] as const;
