export const mahabharatTimelineEvents = [
  {
    slug: "shantanu-and-ganga",
    title: "Shantanu and the River Ganga",
    dateLabel: "Three generations before the war",
    sequenceOrder: 1,
    locationSlug: "hastinapura",
    provenanceTag: "itihasa" as const,
    summary:
      "King Shantanu marries the river-goddess Ganga under a vow never to question her. She drowns seven of their newborn sons in her own waters; when he breaks his silence to stop her at the eighth, she departs — leaving him that surviving son, Devavrata, who will one day be known as Bhishma.",
    figures: [
      { slug: "shantanu", roleInEvent: "Marries Ganga under a vow of silence" },
      { slug: "ganga", roleInEvent: "Drowns seven sons, spares the eighth" },
      { slug: "bhishma", roleInEvent: "The eighth son, spared" },
    ],
  },
  {
    slug: "bhishmas-vow",
    title: "The Vow of Bhishma",
    dateLabel: "Three generations before the war",
    sequenceOrder: 2,
    locationSlug: "hastinapura",
    provenanceTag: "itihasa" as const,
    summary:
      "Shantanu longs to marry Satyavati, but her father demands that her sons — not Devavrata — inherit the throne. To free his father, Devavrata renounces the crown and swears never to marry or father heirs. The vow is so severe it earns him the name Bhishma, 'the terrible one' — and it leaves the main Kuru line without an heir of its own.",
    figures: [
      { slug: "bhishma", roleInEvent: "Renounces the throne and swears celibacy" },
      { slug: "shantanu", roleInEvent: "Longs to marry Satyavati" },
      { slug: "satyavati", roleInEvent: "The bride whose condition prompts the vow" },
    ],
  },
  {
    slug: "amba-and-the-brides",
    title: "Amba and the Brides of Kashi",
    dateLabel: "Two generations before the war",
    sequenceOrder: 3,
    locationSlug: "hastinapura",
    provenanceTag: "itihasa" as const,
    summary:
      "To provide heirs for Satyavati's sickly son Vichitravirya, Bhishma carries off three princesses of Kashi from their swayamvara. The eldest, Amba, is released when she declares she loves another — only to be rejected by that man as already won. Holding Bhishma to blame, she vows a revenge that will outlast her own life, returning as Shikhandi to bring about his fall.",
    figures: [
      { slug: "bhishma", roleInEvent: "Abducts the three princesses of Kashi" },
      { slug: "amba", roleInEvent: "Cast off, vows revenge" },
    ],
  },
  {
    slug: "the-niyoga-births",
    title: "The Birth of the Three Brothers",
    dateLabel: "Two generations before the war",
    sequenceOrder: 4,
    locationSlug: "hastinapura",
    provenanceTag: "itihasa" as const,
    summary:
      "With Vichitravirya dead childless and Bhishma bound by his vow, Satyavati summons her firstborn son, the sage Vyasa, to father heirs on the widowed queens. Ambika shuts her eyes and bears the blind Dhritarashtra; Ambalika turns pale and bears Pandu; a maid sent in a queen's place bears the clear-eyed Vidura — each brother marked at birth by the manner of his conception.",
    figures: [
      { slug: "vyasa", roleInEvent: "Fathers the heirs by niyoga" },
      { slug: "satyavati", roleInEvent: "Summons Vyasa to save the line" },
      { slug: "dhritarashtra", roleInEvent: "Born blind" },
      { slug: "pandu", roleInEvent: "Born pale" },
      { slug: "vidura", roleInEvent: "Born of a maid" },
    ],
  },
  {
    slug: "pandu-and-the-curse",
    title: "The Curse of Pandu",
    dateLabel: "A generation before the war",
    sequenceOrder: 5,
    locationSlug: "shatashringa",
    provenanceTag: "itihasa" as const,
    summary:
      "With the blind Dhritarashtra passed over, Pandu takes the throne and weds Kunti and Madri, while Bhishma marries Dhritarashtra to Gandhari — who binds her own eyes to share her husband's blindness. Hunting in the forest, Pandu kills a sage in the form of a mating deer and is cursed to die the moment he embraces a wife. He renounces the crown and withdraws to the mountains, leaving Dhritarashtra to rule in his place.",
    figures: [
      { slug: "pandu", roleInEvent: "Cursed, renounces the throne" },
      { slug: "gandhari", roleInEvent: "Binds her eyes for the blind king" },
      { slug: "dhritarashtra", roleInEvent: "Takes the throne in Pandu's absence" },
    ],
  },
  {
    slug: "birth-of-the-pandavas",
    title: "The Birth of the Pandavas",
    dateLabel: "A generation before the war",
    sequenceOrder: 6,
    locationSlug: "shatashringa",
    provenanceTag: "itihasa" as const,
    summary:
      "Unable to father children under the curse, Pandu turns to a boon Kunti carries — a mantra to summon any god and bear his son. Kunti calls Dharma, Vayu, and Indra, bearing Yudhishthira, Bhima, and Arjuna; Madri calls the Ashwins and bears the twins Nakula and Sahadeva. When Pandu at last forgets himself and embraces Madri, the curse takes him, and Madri follows him onto the pyre.",
    figures: [
      { slug: "kunti", roleInEvent: "Summons the gods for sons" },
      { slug: "madri", roleInEvent: "Bears the twins, then dies with Pandu" },
      { slug: "pandu", roleInEvent: "Dies by the curse" },
      { slug: "yudhishthira", roleInEvent: "Firstborn, son of Dharma" },
      { slug: "bhima", roleInEvent: "Son of Vayu" },
      { slug: "arjuna", roleInEvent: "Son of Indra" },
      { slug: "nakula", roleInEvent: "Twin son of the Ashwins" },
      { slug: "sahadeva", roleInEvent: "Twin son of the Ashwins" },
    ],
  },
  {
    slug: "birth-of-the-kauravas",
    title: "The Birth of the Hundred Kauravas",
    dateLabel: "A generation before the war",
    sequenceOrder: 7,
    locationSlug: "hastinapura",
    provenanceTag: "itihasa" as const,
    summary:
      "Gandhari's pregnancy drags on unnaturally long; in despair she strikes her own womb and delivers a lifeless mass, which Vyasa divides and incubates into a hundred sons and a daughter. Duryodhana is born first, to a chorus of ill omens — jackals, braying, a darkening sky. Vidura urges the king to give up this one child for the good of the line, and Dhritarashtra, unable to, keeps him: the first of the indulgences that lead to war.",
    figures: [
      { slug: "gandhari", roleInEvent: "Mother of the hundred" },
      { slug: "duryodhana", roleInEvent: "Firstborn, marked by ill omens" },
      { slug: "dhritarashtra", roleInEvent: "Refuses to give up his son" },
      { slug: "vidura", roleInEvent: "Counsels abandoning the child" },
    ],
  },
  {
    slug: "the-trial-of-arms",
    title: "The Trial of Arms",
    dateLabel: "In the princes' youth",
    sequenceOrder: 8,
    locationSlug: "hastinapura",
    provenanceTag: "itihasa" as const,
    summary:
      "The cousins grow up together and badly — Bhima's strength torments the Kauravas, and Duryodhana repays it by poisoning him and casting him into the river, from which he returns stronger. Bhishma engages the master Drona to train them all; Arjuna becomes his favourite. To keep Arjuna unrivalled, Drona demands the thumb of the self-taught archer Ekalavya, who gives it without protest.",
    figures: [
      { slug: "drona", roleInEvent: "Master of arms to the princes" },
      { slug: "arjuna", roleInEvent: "Drona's foremost pupil" },
      { slug: "ekalavya", roleInEvent: "Surrenders his thumb as the teacher's fee" },
      { slug: "bhima", roleInEvent: "Poisoned by Duryodhana, survives" },
    ],
  },
  {
    slug: "karna-at-the-tournament",
    title: "Karna at the Tournament",
    dateLabel: "In the princes' youth",
    sequenceOrder: 9,
    locationSlug: "hastinapura",
    provenanceTag: "itihasa" as const,
    summary:
      "At the graduation tournament where Arjuna is meant to shine, a stranger steps forward and matches him feat for feat — Karna. Asked to name a royal line and unable to, he is mocked as a charioteer's son. Duryodhana crowns him king of Anga on the spot, buying a lifelong ally. Only Kunti, watching in silence, knows the stranger is her own firstborn — and so the Pandavas' eldest brother, raised up to destroy them.",
    figures: [
      { slug: "karna", roleInEvent: "The challenger, shamed then crowned" },
      { slug: "duryodhana", roleInEvent: "Crowns Karna king of Anga" },
      { slug: "arjuna", roleInEvent: "The rival Karna comes to match" },
      { slug: "kunti", roleInEvent: "Recognizes her firstborn, stays silent" },
    ],
  },
  {
    slug: "the-house-of-lac",
    title: "The House of Lac",
    dateLabel: "In the princes' youth",
    sequenceOrder: 10,
    locationSlug: "varanavata",
    provenanceTag: "itihasa" as const,
    summary:
      "Alarmed by the Pandavas' growing favour, Duryodhana has them sent to Varanavata to stay in a palace secretly built of lac and pitch, meaning to burn them as they sleep. Warned by Vidura in coded speech, they dig an escape tunnel, set the fire themselves on a chosen night, and slip away — leaving Hastinapura to believe them dead and freeing them to move unseen.",
    figures: [
      { slug: "duryodhana", roleInEvent: "Plots the fire" },
      { slug: "vidura", roleInEvent: "Warns the Pandavas" },
      { slug: "bhima", roleInEvent: "Leads the escape" },
    ],
  },
  {
    slug: "draupadis-swayamvara",
    title: "The Swayamvara of Draupadi",
    dateLabel: "During the years in hiding",
    sequenceOrder: 11,
    locationSlug: "panchala",
    provenanceTag: "itihasa" as const,
    summary:
      "At Drupada's court, suitors must string a great bow and pierce a turning target's eye. Disguised as a brahmin, Arjuna alone succeeds and wins Draupadi. Back home, Kunti's unwitting instruction to 'share what you have brought' — spoken before she sees what it is — makes Draupadi wife to all five brothers, and reveals the Pandavas alive and allied to Panchala.",
    figures: [
      { slug: "draupadi", roleInEvent: "Won at the swayamvara" },
      { slug: "arjuna", roleInEvent: "Wins the contest in disguise" },
      { slug: "kunti", roleInEvent: "Whose word makes Draupadi wife to five" },
      { slug: "drupada", roleInEvent: "Father of the bride, new ally" },
      { slug: "dhrishtadyumna", roleInEvent: "Draupadi's brother, born of the same fire" },
    ],
  },
  {
    slug: "the-rajasuya",
    title: "The Rajasuya and the Hall of Illusions",
    dateLabel: "The height of the Pandavas' fortune",
    sequenceOrder: 12,
    locationSlug: "indraprastha",
    provenanceTag: "itihasa" as const,
    summary:
      "Given the wilderness of Khandavaprastha, the Pandavas raise the shining city of Indraprastha, where the architect Maya builds a hall of illusions. Yudhishthira performs the Rajasuya, the imperial rite that proclaims him paramount king. Visiting, Duryodhana is made a fool of in the trick-hall and laughed at — a humiliation he leaves resolved to answer, whatever it costs.",
    figures: [
      { slug: "yudhishthira", roleInEvent: "Performs the Rajasuya" },
      { slug: "krishna", roleInEvent: "Honoured first among the guests" },
      { slug: "duryodhana", roleInEvent: "Humiliated in the hall" },
      { slug: "draupadi", roleInEvent: "Whose laughter stings" },
    ],
  },
  {
    slug: "game-of-dice",
    title: "The Game of Dice at Hastinapura",
    dateLabel: "Before the war",
    sequenceOrder: 13,
    locationSlug: "hastinapura",
    provenanceTag: "itihasa" as const,
    summary:
      "Shakuni, uncle to the Kauravas, goads Yudhishthira into a rigged game of dice. Yudhishthira stakes and loses his kingdom, his brothers, and finally Draupadi — who is dragged into the court and humiliated. The Pandavas are exiled for thirteen years as a condition of the wager.",
    figures: [
      { slug: "yudhishthira", roleInEvent: "Stakes and loses everything" },
      { slug: "shakuni", roleInEvent: "Rolls the loaded dice for Duryodhana" },
      { slug: "draupadi", roleInEvent: "Staked and humiliated in the court" },
    ],
  },
  {
    slug: "the-exile-and-disguise",
    title: "The Years of Exile",
    dateLabel: "The thirteen years of exile",
    sequenceOrder: 14,
    locationSlug: "kamyaka",
    provenanceTag: "itihasa" as const,
    summary:
      "The dice game's terms send the Pandavas away for thirteen years — twelve in the forest, one spent in disguise without being found. Arjuna wins celestial weapons, including the Pashupata from Shiva; Yudhishthira passes the Yaksha's test of questions. The last year they serve, hidden, in Virata's court, until a cattle-raid forces Arjuna to reveal himself — and the term is fulfilled.",
    figures: [
      { slug: "arjuna", roleInEvent: "Wins celestial weapons; breaks his disguise" },
      { slug: "yudhishthira", roleInEvent: "Answers the Yaksha's questions" },
      { slug: "bhima", roleInEvent: "Serves hidden, kills Kichaka" },
      { slug: "draupadi", roleInEvent: "Serves as the queen's maid in hiding" },
    ],
  },
  {
    slug: "krishnas-peace-embassy",
    title: "Krishna's Embassy for Peace",
    dateLabel: "On the eve of war",
    sequenceOrder: 15,
    locationSlug: "hastinapura",
    provenanceTag: "itihasa" as const,
    summary:
      "As the Pandavas' envoy, Krishna asks Duryodhana for a settlement as small as five villages, one for each brother. Duryodhana refuses to yield land 'without war, not even enough to fit on the point of a needle' — making the conflict unavoidable.",
    figures: [{ slug: "krishna", roleInEvent: "Envoy for peace" }],
  },
  {
    slug: "bhagavad-gita",
    title: "The Bhagavad Gita on the Battlefield",
    dateLabel: "Day 1 of the war",
    sequenceOrder: 16,
    locationSlug: "kurukshetra",
    provenanceTag: "itihasa" as const,
    summary:
      "With both armies arrayed and ready, Arjuna asks Krishna to draw his chariot between the lines — and seeing teachers, elders, and kin on the opposing side, he loses the will to fight. Krishna's response, on duty, the self, and acting without attachment to outcome, becomes the Bhagavad Gita.",
    figures: [
      { slug: "krishna", roleInEvent: "Counsels Arjuna" },
      { slug: "arjuna", roleInEvent: "In crisis of conscience" },
    ],
  },
  {
    slug: "fall-of-bhishma",
    title: "The Fall of Bhishma",
    dateLabel: "Day 10 of the war",
    sequenceOrder: 17,
    locationSlug: "kurukshetra",
    provenanceTag: "itihasa" as const,
    summary:
      "Bhishma has vowed never to fight one born a woman. Arjuna advances behind Shikhandi, and Bhishma lowers his weapons — falling to a bed of arrows. Having been granted the power to choose the hour of his own death, he lingers there until an auspicious moment before he dies.",
    figures: [
      { slug: "bhishma", roleInEvent: "Falls, mortally wounded" },
      { slug: "arjuna", roleInEvent: "Fells Bhishma" },
      { slug: "shikhandi", roleInEvent: "The reborn Amba, at whose approach Bhishma lowers his bow" },
    ],
  },
  {
    slug: "death-of-abhimanyu",
    title: "The Death of Abhimanyu",
    dateLabel: "Day 13 of the war",
    sequenceOrder: 18,
    locationSlug: "kurukshetra",
    provenanceTag: "itihasa" as const,
    summary:
      "With the elder Pandavas drawn off and blocked from following, the Kaurava army closes the Chakravyuha formation around Abhimanyu, who knows how to break in but never learned how to break out. Multiple warriors converge on him at once — a breach of the war's one-on-one code that becomes one of the Pandavas' deepest grievances.",
    figures: [
      { slug: "abhimanyu", roleInEvent: "Trapped and killed" },
      { slug: "jayadratha", roleInEvent: "Blocks the Pandavas from following him in" },
    ],
  },
  {
    slug: "jayadrathas-death",
    title: "The Fall of Jayadratha",
    dateLabel: "Day 14 of the war",
    sequenceOrder: 19,
    locationSlug: "kurukshetra",
    provenanceTag: "itihasa" as const,
    summary:
      "Blamed for holding the Pandavas back while Abhimanyu was killed, Jayadratha becomes the target of Arjuna's vow: to kill him before sundown or die by his own hand. As the day runs out and Jayadratha is hidden behind the Kaurava lines, Krishna veils the sun to counterfeit sunset; Jayadratha shows himself, and Arjuna strikes off his head — carrying it by arrow into his meditating father's lap to escape a rebounding curse.",
    figures: [
      { slug: "jayadratha", roleInEvent: "Beheaded to fulfil Arjuna's vow" },
      { slug: "arjuna", roleInEvent: "Kills him before the false sunset" },
      { slug: "krishna", roleInEvent: "Veils the sun" },
    ],
  },
  {
    slug: "death-of-ghatotkacha",
    title: "The Death of Ghatotkacha",
    dateLabel: "Night of Day 14",
    sequenceOrder: 20,
    locationSlug: "kurukshetra",
    provenanceTag: "itihasa" as const,
    summary:
      "In the night battle, Bhima's rakshasa son Ghatotkacha looses his powers on the Kaurava army until it faces annihilation. Left no choice, Karna hurls the Vasavi Shakti — the single infallible dart he had hoarded all war to kill Arjuna — and Ghatotkacha, dying, swells to enormous size and crushes a division beneath him. Krishna openly rejoices: the weapon that could have killed Arjuna is spent.",
    figures: [
      { slug: "ghatotkacha", roleInEvent: "Killed by the Vasavi Shakti" },
      { slug: "karna", roleInEvent: "Forced to spend the weapon saved for Arjuna" },
      { slug: "krishna", roleInEvent: "Rejoices at the trade" },
    ],
  },
  {
    slug: "fall-of-drona",
    title: "The Fall of Drona",
    dateLabel: "Day 15 of the war",
    sequenceOrder: 21,
    locationSlug: "kurukshetra",
    provenanceTag: "itihasa" as const,
    summary:
      "Unable to defeat Drona in open combat, the Pandavas let him hear that 'Ashwatthama is dead' — true only of an elephant given that name, not his son. Drona lays down his weapons to grieve, and is killed by Dhrishtadyumna, Draupadi's brother, born for the purpose of ending him.",
    figures: [
      { slug: "krishna", roleInEvent: "Suggests the deception" },
      { slug: "yudhishthira", roleInEvent: "Speaks the half-truth that disarms Drona" },
      { slug: "dhrishtadyumna", roleInEvent: "Beheads the disarmed Drona" },
      { slug: "drona", roleInEvent: "Lays down his weapons and is killed" },
    ],
  },
  {
    slug: "death-of-dushasana",
    title: "The Death of Dushasana",
    dateLabel: "Day 16 of the war",
    sequenceOrder: 22,
    locationSlug: "kurukshetra",
    provenanceTag: "itihasa" as const,
    summary:
      "On the sixteenth day Bhima runs down Dushasana — the brother who dragged Draupadi into the assembly — and fulfils to the letter the vow he swore there, tearing open his chest, a horror the field watches in silence. Draupadi's thirteen-year-old grievance is answered, and one of Bhima's dice-game oaths is paid in full.",
    figures: [
      { slug: "dushasana", roleInEvent: "Killed, fulfilling Bhima's blood-oath" },
      { slug: "bhima", roleInEvent: "Fulfils his vow from the dice game" },
      { slug: "draupadi", roleInEvent: "Her humiliation avenged" },
    ],
  },
  {
    slug: "death-of-karna",
    title: "The Death of Karna",
    dateLabel: "Day 17 of the war",
    sequenceOrder: 23,
    locationSlug: "kurukshetra",
    provenanceTag: "itihasa" as const,
    summary:
      "With his chariot wheel caught in the mud and a curse robbing him of the incantation for his greatest weapon, Karna is killed by Arjuna — Krishna having kept silent, until near the very end, on the fact that Karna was Kunti's eldest son, and so the Pandavas' own brother.",
    figures: [
      { slug: "karna", roleInEvent: "Killed" },
      { slug: "arjuna", roleInEvent: "Kills Karna" },
      { slug: "krishna", roleInEvent: "Guides Arjuna's chariot" },
    ],
  },
  {
    slug: "death-of-duryodhana",
    title: "The Death of Duryodhana",
    dateLabel: "Day 18 of the war",
    sequenceOrder: 24,
    locationSlug: "kurukshetra",
    provenanceTag: "itihasa" as const,
    summary:
      "In the war's final duel, Bhima and Duryodhana fight to exhaustion with maces. At Krishna's private signal, Bhima strikes below the waist — against the rules of fair combat — and breaks Duryodhana's thigh, fulfilling the vow he swore at the dice game years before.",
    figures: [
      { slug: "duryodhana", roleInEvent: "Mortally wounded" },
      { slug: "bhima", roleInEvent: "Breaks Duryodhana's thigh with his mace" },
      { slug: "krishna", roleInEvent: "Signals the killing blow" },
    ],
  },
  {
    slug: "ashwatthamas-night-raid",
    title: "Ashwatthama's Night Raid",
    dateLabel: "Night after Day 18",
    sequenceOrder: 25,
    locationSlug: "kurukshetra",
    provenanceTag: "itihasa" as const,
    summary:
      "Enraged by his father Drona's death and Duryodhana's dying wish for revenge, Ashwatthama slips into the sleeping Pandava camp with two allies and kills the camp's defenders and the five sons born to the Pandavas — a massacre the epic does not let the 'winning' side walk away from cleanly.",
    figures: [
      { slug: "ashwatthama", roleInEvent: "Slaughters the sleeping camp" },
      { slug: "draupadi", roleInEvent: "Her five sons killed as they sleep" },
      { slug: "dhrishtadyumna", roleInEvent: "Killed in his sleep" },
      { slug: "shikhandi", roleInEvent: "Killed in the raid" },
      { slug: "krishna", roleInEvent: "Curses Ashwatthama to wander" },
    ],
  },
  {
    slug: "sorrow-of-victory",
    title: "The Sorrow of Victory",
    dateLabel: "After the war",
    sequenceOrder: 26,
    locationSlug: "kurukshetra",
    provenanceTag: "itihasa" as const,
    summary:
      "The women come onto the field to find their dead. Surveying her hundred lost sons, Gandhari curses Krishna — that he who let the Kuru house destroy itself will watch his own Yadava clan tear itself apart the same way. Kunti at last confesses that the Karna they killed was their eldest brother, and Yudhishthira, crowned over a Hastinapura emptied of a generation, takes the throne as a grief rather than a triumph.",
    figures: [
      { slug: "gandhari", roleInEvent: "Curses Krishna over her dead sons" },
      { slug: "krishna", roleInEvent: "Accepts the curse" },
      { slug: "kunti", roleInEvent: "Reveals that Karna was their brother" },
      { slug: "yudhishthira", roleInEvent: "Crowned over a hollow victory" },
      { slug: "dhritarashtra", roleInEvent: "Later retires to the forest to die" },
    ],
  },
  {
    slug: "bhishmas-final-teaching",
    title: "Bhishma's Teaching and Passing",
    dateLabel: "After the war",
    sequenceOrder: 27,
    locationSlug: "kurukshetra",
    provenanceTag: "itihasa" as const,
    summary:
      "Guilt-stricken and half-refusing his crown, Yudhishthira is brought by Krishna to the still-living Bhishma, who has held off death on his bed of arrows for the auspicious hour. From there the grandfather delivers the epic's longest teaching — on dharma, kingship, and how to live in the world the war has made — and only when it is done, at the winter solstice, lets his life go. Yudhishthira later performs the Ashwamedha to expiate the bloodshed.",
    figures: [
      { slug: "bhishma", roleInEvent: "Teaches from the bed of arrows, then dies" },
      { slug: "yudhishthira", roleInEvent: "Receives the instruction on how to rule" },
      { slug: "krishna", roleInEvent: "Sends the king to learn" },
    ],
  },
  {
    slug: "great-departure",
    title: "The Great Departure",
    dateLabel: "Long after the war",
    sequenceOrder: 28,
    locationSlug: "swargarohini",
    provenanceTag: "itihasa" as const,
    summary:
      "Their reign ended and Krishna gone as Gandhari foretold, the five Pandavas and Draupadi renounce the throne and walk north toward the Himalayas and heaven. One by one they fall on the ascent, each for a hidden flaw, until only Yudhishthira and a stray dog remain. Offered heaven but told to abandon the dog, he refuses — and the dog is revealed as the god Dharma, his own father, and the refusal his final test.",
    figures: [
      { slug: "yudhishthira", roleInEvent: "The last to fall; refuses to abandon the dog" },
      { slug: "draupadi", roleInEvent: "First to fall on the ascent" },
      { slug: "bhima", roleInEvent: "Falls on the ascent" },
      { slug: "arjuna", roleInEvent: "Falls on the ascent" },
      { slug: "nakula", roleInEvent: "Falls on the ascent" },
      { slug: "sahadeva", roleInEvent: "Falls on the ascent" },
    ],
  },
];
